package:
  name: slicerecon
  version: 1.2.0.beta

source:
  git_url: https://github.com/cicwi/RECAST3D
  git_tag: develop

test:
  imports:
    - slicerecon
  commands:
    - test -f $PREFIX/bin/slicerecon_server      # [unix]

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - pybind11
    - pkg-config                        # [unix]
    - cmake
    - make
    - astra-toolbox
    - fftw
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - boost
    - zeromq=4
    - eigen
    - pybind11
    - zlib
    - astra-toolbox
    - fftw
  run:
    - python
    - zeromq=4
    - zlib
    - astra-toolbox

about:
  home: https://github.com/cicwi/RECAST3D
  license: GPLv3
  summary: 'SliceRecon: Reconstruction of arbitrary slices in tomography.'
