package:
  name: slicerecon
  version: 1.1.0

source:
  git_url: https://github.com/jwbuurlage/RECAST3D
  git_tag: master

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config                        # [unix]
    - cmake
    - make
    - astra-toolbox
    - fftw
  host:
    - boost
    - zeromq=4
    - eigen
    - pybind11
    - zlib
    - astra-toolbox
    - fftw
  run:
    - zeromq=4
    - zlib
    - astra-toolbox

test:
  commands:
    - test -f $PREFIX/bin/slicerecon_server      # [unix]

about:
  home: https://github.com/jwbuurlage/RECAST3D
  license: GPLv3
  summary: 'SliceRecon: Reconstruction of arbitrary slices in tomography.'
