package:
  name: recast3d
  version: 1.1.0

source:
  git_url: https://github.com/cicwi/RECAST3D
  git_tag: master

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-common') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('xorg-x11-server-common') }}
    - {{ cdt('xorg-x11-server-xvfb') }}
    - {{ cdt('xorg-x11-util-macros') }}
    - {{ cdt('xorg-x11-xauth') }}
    - {{ cdt('libxrandr-devel') }}
    - {{ cdt('libxinerama-devel') }}
    - {{ cdt('libxcursor-devel') }}
    - {{ cdt('libxau-devel') }}
    - {{ cdt('libdrm-devel') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-libegl-devel') }}    # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxrender-devel') }}     # [linux]
    - {{ cdt('libxcomposite-devel') }}  # [linux]
    - {{ cdt('libxcursor-devel') }}     # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libselinux-devel') }}     # [linux]
    - {{ cdt('libxrandr-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}           # [linux]
    - {{ cdt('libxdamage-devel') }}     # [linux]
    - {{ cdt('libxfixes') }}            # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('libxxf86vm') }}           # [linux]
    - pkg-config                        # [unix]
    - cmake
    - make
  host:
    - boost
    - zeromq=4
    - eigen
    - pybind11
    - libxcb                            # [linux]
    - zlib
  run:
    - zeromq=4
    - eigen
    - libxcb                            # [linux]
    - zlib

test:
  commands:
    - test -f $PREFIX/bin/recast3d      # [unix]


about:
  home: https://github.com/cicwi/RECAST3D
  license: GPLv3
  summary: 'RECAST3D: Real-time visualization tool for tomographic data.'
