{% set data = load_setup_py_data() %}

package:
  name: tomopackets
  version: 1.1.0

source:
  # path: ../
  git_url: https://github.com/jwbuurlage/RECAST3D
  git_tag: master

build:
  number: 0
test:
  imports:
    - tomop

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - boost-cpp
    - pybind11
    - zeromq=4
    - cmake_setuptools
  run:
    - python
    - zeromq=4
    - cmake_setuptools

about:
  home: https://github.com/jwbuurlage/RECAST3D
  license: GPLv3
  summary: 'TomoPackets'
