{% set data = load_setup_py_data() %}

package:
  name: tomopackets
  version: 1.1.0

source:
  # path: ../
  git_url: https://github.com/jwbuurlage/RECAST3D
  git_tag: master

build:
  number: 0

test:
  imports:
    - tomop

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - pybind11
    - boost
    - cmake
    - make
    - numpy
  host:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - zeromq=4

about:
  home: https://github.com/jwbuurlage/RECAST3D
  license: LICENSE.md
  summary: 'TomoPackets'
