site_name: RECAST3D
repo_name: cicwi/RECAST3D
repo_url: https://github.com/cicwi/RECAST3D
copyright: "RECAST3D is licensed under the <a href='https://github.com/cicwi/RECAST3D/blob/master/LICENSE.md'>GPL license</a>"

theme: 'material'

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - codehilite
    - toc
    - footnotes
    - pymdownx.arithmatex

docs_dir: pages

nav:
  - Home: 'index.md'
  - Installing: 'live_software_stack.md'
  - User Guide: 'user_guide.md'
  - Release Notes: 'changelog.md'

extra:
    palette:
        primary: 'blue grey'
        accent: 'orange'
    social:
        - type: 'github-alt'
          link: 'https://github.com/jwbuurlage'
        - type: 'twitter'
          link: 'https://twitter.com/jwbuurlage'
    logo: 'images/logo.svg'

